### PR TITLE
Setup GithubCI using github workflows

### LINKED ISSUE #2: Create GithubCI to run project checks

### PR DESCRIPTION
**Pull request by a-mere-peasant**
Closes #2

### CODE REVIEW

**Comment by a-mere-peasant** [comment]
I've just added the blank jobs file , would you like me to add something like a greeting for new contributors as well?

**Comment by faogustavo** [comment]
@a-mere-peasant can you set up a basic Gradle test flow for JVM, please?

The command is `./gradlew jvmTest`

**Comment by a-mere-peasant** [comment]
Please let me know if there is  anything else to be added or this command has to be run differently.

**Comment by faogustavo** [comment]
Nice man!
Thanks for the contribution

**Pull request merged**
